//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaHangouts.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class instahangoutsEntities : DbContext
    {
        public instahangoutsEntities()
            : base("name=instahangoutsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogData> LogDatas { get; set; }
        public virtual DbSet<EventAttendanceAssoc> EventAttendanceAssocs { get; set; }
        public virtual DbSet<GroupDetail> GroupDetails { get; set; }
        public virtual DbSet<PlanEvent> PlanEvents { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<GroupUserAssoc> GroupUserAssocs { get; set; }
        public virtual DbSet<LogsInfo> LogsInfoes { get; set; }
        public virtual DbSet<MailTemplate> MailTemplates { get; set; }
    
        public virtual ObjectResult<SP_WelcomeEvents_Result> SP_WelcomeEvents(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WelcomeEvents_Result>("SP_WelcomeEvents", userIdParameter);
        }
    }
}
