//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaHangouts.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int Id { get; set; }
        public string Application { get; set; }
        public Nullable<System.DateTime> Logged { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string Source { get; set; }
    }
}
