//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaHangouts.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        public int MailID { get; set; }
        public string MailCode { get; set; }
        public string Description { get; set; }
        public string MailSubject { get; set; }
        public string Template { get; set; }
        public string ToWhome { get; set; }
        public string CcWhome { get; set; }
        public string BccWhome { get; set; }
    }
}
