//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaHangouts.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanEvent()
        {
            this.EventAttendanceAssocs = new HashSet<EventAttendanceAssoc>();
        }
    
        public int EventId { get; set; }
        public string EventTypeCategory { get; set; }
        public string EventType { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public int EventHostUserId { get; set; }
        public bool WantFood { get; set; }
        public bool IncludeGames { get; set; }
        public bool IncludeFood { get; set; }
        public string EventDescription { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string TimeZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAttendanceAssoc> EventAttendanceAssocs { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
